[package]
name = "play_together_fishing"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30.13"
ctrlc = "3.4.4"
winapi = { version = "0.3.9", features = ["winnt", "memoryapi", "processthreadsapi", "handleapi"] }
memchr = "2.7.1"